version: "3"
services: 
  springboot-app:
   # container_name: spring-app
    image: abhi96dock/springbooot-app:0.1
    restart: always
    build: .
    ports:
      - 8087:8080 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
      -  C:\Users\user\Downloads\mysql_vol_map:/var/lib/mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
        